version: '3.6'
services:
  server:
    build:
      context: .
      dockerfile: .docker/api/dev.dockerfile
    container_name: profiling-api
    ports:
      - '13000:13000'
    networks:
      - profiling-network
    volumes:
      - './:/usr/src/app'

  # mongodb://username:password@localhost:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
  mongodb:
    container_name: profiling-db
    build:
      context: .
      dockerfile: .docker/mongo/dev.dockerfile
    #    make data persistent by using volume.
    #    volumes:
    #      - ./.docker/mongo/data/:/data/db/
    ports:
      - 27017:27017
      - 28017:28017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: profiling-api
    volumes:
      - ./.docker/mongo/seed/:/docker-entrypoint-initdb.d/
    networks:
      - profiling-network

  # localhost:8081
  mongo-express:
    image: mongo-express
    container_name: profiling-db-access
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: profiling-db
    depends_on:
      - mongodb
    networks:
      - profiling-network

networks:
  profiling-network:
    driver: bridge
